/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Axel y Ampy
 */
import Controlador.ControladorDepartamentos;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        
        DefaultMutableTreeNode departamentos = new DefaultMutableTreeNode("Departamentos");
        DefaultMutableTreeNode ingenieriaMantenimiento = new DefaultMutableTreeNode("Ingenieria y Mantenimiento");
        DefaultMutableTreeNode avisos= new DefaultMutableTreeNode("Avisos");
        ingenieriaMantenimiento.insert(avisos,0);
        departamentos.insert(ingenieriaMantenimiento, 0);
        TreeModel sad = new DefaultTreeModel(departamentos);
        
        
      jTree1.setModel(sad);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPTA = new javax.swing.JLabel();
        lblTMEF = new javax.swing.JLabel();
        lblMPT = new javax.swing.JLabel();
        lblTMR = new javax.swing.JLabel();
        lblOEE = new javax.swing.JLabel();
        lblOE = new javax.swing.JLabel();
        lblLEF = new javax.swing.JLabel();
        lblICM = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblIngenieriaYMantenimiento = new javax.swing.JLabel();
        pnlIngYMantenimiento = new javax.swing.JPanel();
        lblAvisos = new javax.swing.JLabel();
        pnlAvisos = new javax.swing.JPanel();
        lblNuevoAviso = new javax.swing.JLabel();
        lblOT = new javax.swing.JLabel();
        pnlOT = new javax.swing.JPanel();
        lblNuevaOT = new javax.swing.JLabel();
        lblPM = new javax.swing.JLabel();
        pnlPM = new javax.swing.JPanel();
        lblNuevoPM = new javax.swing.JLabel();
        lblConsultaPM = new javax.swing.JLabel();
        lblProduccion1 = new javax.swing.JLabel();
        lblRRHH1 = new javax.swing.JLabel();
        lblFinanzas1 = new javax.swing.JLabel();
        lblLogistica1 = new javax.swing.JLabel();
        lblProyecto1 = new javax.swing.JLabel();
        lblCalidad1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFiltro.setName("txtCodigoOperacion"); // NOI18N

        jLabel1.setText("Codigo de Operacion");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de KPI"));

        lblPTA.setText("Porcentaje de tratamiento de avisos (PTA)");

        lblTMEF.setText("Tiempo medio entre fallos (TMEF)");

        lblMPT.setText("Mantenimiento productivo total (MPT)");

        lblTMR.setText("Tiempo medio de respuesta (TMR)");

        lblOEE.setText("Eficacia general del equipo (OEE)");

        lblOE.setText("Paro de maquina propio y de terceros (OE)");

        lblLEF.setText("Eficiencia de maquina (LEF)");

        lblICM.setText("Indice de cumplimiento de mantenimiento (ICM)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion Departamentos"));

        lblIngenieriaYMantenimiento.setText("Ingenieria y Mantenimiento");

        lblAvisos.setText("Avisos");

        lblNuevoAviso.setText("Nuevo aviso (IM01)");

        javax.swing.GroupLayout pnlAvisosLayout = new javax.swing.GroupLayout(pnlAvisos);
        pnlAvisos.setLayout(pnlAvisosLayout);
        pnlAvisosLayout.setHorizontalGroup(
            pnlAvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvisosLayout.createSequentialGroup()
                .addComponent(lblNuevoAviso)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        pnlAvisosLayout.setVerticalGroup(
            pnlAvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevoAviso)
        );

        lblOT.setText("Orden de Trabajo");

        lblNuevaOT.setText("Nueva OT");

        javax.swing.GroupLayout pnlOTLayout = new javax.swing.GroupLayout(pnlOT);
        pnlOT.setLayout(pnlOTLayout);
        pnlOTLayout.setHorizontalGroup(
            pnlOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOTLayout.createSequentialGroup()
                .addComponent(lblNuevaOT)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlOTLayout.setVerticalGroup(
            pnlOTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevaOT)
        );

        lblPM.setText("Programa de Mantenimiento");

        lblNuevoPM.setText("Nuevo PM");

        lblConsultaPM.setText("Consulta PM");

        javax.swing.GroupLayout pnlPMLayout = new javax.swing.GroupLayout(pnlPM);
        pnlPM.setLayout(pnlPMLayout);
        pnlPMLayout.setHorizontalGroup(
            pnlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPMLayout.createSequentialGroup()
                .addGroup(pnlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoPM)
                    .addComponent(lblConsultaPM))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPMLayout.setVerticalGroup(
            pnlPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPMLayout.createSequentialGroup()
                .addComponent(lblNuevoPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConsultaPM))
        );

        javax.swing.GroupLayout pnlIngYMantenimientoLayout = new javax.swing.GroupLayout(pnlIngYMantenimiento);
        pnlIngYMantenimiento.setLayout(pnlIngYMantenimientoLayout);
        pnlIngYMantenimientoLayout.setHorizontalGroup(
            pnlIngYMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngYMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngYMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisos)
                    .addComponent(lblOT)
                    .addComponent(lblPM)
                    .addGroup(pnlIngYMantenimientoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlIngYMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlOT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIngYMantenimientoLayout.setVerticalGroup(
            pnlIngYMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngYMantenimientoLayout.createSequentialGroup()
                .addComponent(lblAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblProduccion1.setText("Produccion");

        lblRRHH1.setText("Recursos Humanos");

        lblFinanzas1.setText("Finanzas");

        lblLogistica1.setText("Logistica");

        lblProyecto1.setText("Proyecto");

        lblCalidad1.setText("Calidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIngenieriaYMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIngYMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProyecto1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogistica1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRRHH1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduccion1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinanzas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalidad1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngenieriaYMantenimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIngYMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinanzas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRRHH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProduccion1)
                .addGap(10, 10, 10)
                .addComponent(lblProyecto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCalidad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogistica1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPTA)
                    .addComponent(lblTMEF)
                    .addComponent(lblMPT)
                    .addComponent(lblTMR)
                    .addComponent(lblOEE)
                    .addComponent(lblOE)
                    .addComponent(lblLEF)
                    .addComponent(lblICM))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(lblPTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTMEF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTMR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOEE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLEF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblICM)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Fallos de Linea"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblAvisos;
    private javax.swing.JLabel lblCalidad1;
    private javax.swing.JLabel lblConsultaPM;
    private javax.swing.JLabel lblFinanzas1;
    private javax.swing.JLabel lblICM;
    private javax.swing.JLabel lblIngenieriaYMantenimiento;
    private javax.swing.JLabel lblLEF;
    private javax.swing.JLabel lblLogistica1;
    private javax.swing.JLabel lblMPT;
    private javax.swing.JLabel lblNuevaOT;
    private javax.swing.JLabel lblNuevoAviso;
    private javax.swing.JLabel lblNuevoPM;
    private javax.swing.JLabel lblOE;
    private javax.swing.JLabel lblOEE;
    private javax.swing.JLabel lblOT;
    private javax.swing.JLabel lblPM;
    private javax.swing.JLabel lblPTA;
    private javax.swing.JLabel lblProduccion1;
    private javax.swing.JLabel lblProyecto1;
    private javax.swing.JLabel lblRRHH1;
    private javax.swing.JLabel lblTMEF;
    private javax.swing.JLabel lblTMR;
    private javax.swing.JPanel pnlAvisos;
    private javax.swing.JPanel pnlIngYMantenimiento;
    private javax.swing.JPanel pnlOT;
    private javax.swing.JPanel pnlPM;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables



    public JTextField getTxtFiltro() {
        return txtFiltro;
    }

    public JLabel getLblAvisos() {
        return lblAvisos;
    }

    public void setLblAvisos(JLabel lblAvisos) {
        this.lblAvisos = lblAvisos;
    }

    public JLabel getLblIngenieriaYMantenimiento() {
        return lblIngenieriaYMantenimiento;
    }

    public void setLblIngenieriaYMantenimiento(JLabel lblIngenieriaYMantenimiento) {
        this.lblIngenieriaYMantenimiento = lblIngenieriaYMantenimiento;
    }

    public JPanel getPnlIngYMantenimiento() {
        return pnlIngYMantenimiento;
    }

    public void setPnlIngYMantenimiento(JPanel pnlIngYMantenimiento) {
        this.pnlIngYMantenimiento = pnlIngYMantenimiento;
    }


    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JLabel getLblNuevoAviso() {
        return lblNuevoAviso;
    }

    public void setLblNuevoAviso(JLabel lblNuevoAviso) {
        this.lblNuevoAviso = lblNuevoAviso;
    }

    public JPanel getPnlAvisos() {
        return pnlAvisos;
    }

    public void setPnlAvisos(JPanel pnlAvisos) {
        this.pnlAvisos = pnlAvisos;
    }

    public JLabel getLblNuevaOT() {
        return lblNuevaOT;
    }

    public void setLblNuevaOT(JLabel lblNuevaOT) {
        this.lblNuevaOT = lblNuevaOT;
    }

    public JLabel getLblNuevoPM() {
        return lblNuevoPM;
    }

    public void setLblNuevoPM(JLabel lblNuevoPM) {
        this.lblNuevoPM = lblNuevoPM;
    }

    public JLabel getLblOT() {
        return lblOT;
    }

    public void setLblOT(JLabel lblOT) {
        this.lblOT = lblOT;
    }

    public JLabel getLblPM() {
        return lblPM;
    }

    public void setLblPM(JLabel lblPM) {
        this.lblPM = lblPM;
    }

    public JPanel getPnlOT() {
        return pnlOT;
    }

    public void setPnlOT(JPanel pnlOT) {
        this.pnlOT = pnlOT;
    }

    public JPanel getPnlPM() {
        return pnlPM;
    }

    public void setPnlPM(JPanel pnlPM) {
        this.pnlPM = pnlPM;
    }

    public JLabel getLblConsultaPM() {
        return lblConsultaPM;
    }

    public void setLblConsultaPM(JLabel lblConsultaPM) {
        this.lblConsultaPM = lblConsultaPM;
    }

    
    
}
